[[pages]]
path = "INICIO.py"
name = "Início 🏘️"
icon = ""

[[pages]]
path = "pages/1_INDUSTRIA_NO_MUNDO.py"
name = "Indústria no Mundo 🌎"
icon = ""

[[pages]]
path = "pages/2_TRADUTOR_GPT.py"
name = "Tradutor GPT Econ 📝"
icon = ""

[[pages]]
path = "pages/3_INFLATION_REDUCTION_ACT.py"
name = "Levantamento IRA ⚖️"
icon = ""

[[pages]]
path = "INICIO.py"
name = ""
icon = ""
is_section = true